### Create Shortlink
POST http://localhost:8888/.netlify/functions/createLink
Content-Type: application/json

{
  "slug": "discord",
  "destination": "https://discord.gg/yip",
  "userId": "123e4567-e89b-12d3-a456-426614174000"
}
